config/routes.rb
Rails.application.routes.draw do
  resources :vehicles do
    resources :vehicle_images
  end
  resources :brands
  resources :vehicle_types
  resources :segments
  resources :fuel_types
  resources :transmissions
  resources :conditions

  root 'vehicles#index'
end

app/models/segment.rb
class Segment < ApplicationRecord
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: %i[ show edit update destroy ]

  # GET /segments or /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1 or /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments or /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: "Segment was successfully created." }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1 or /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: "Segment was successfully updated." }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1 or /segments/1.json
  def destroy
    @segment.destroy!

    respond_to do |format|
      format.html { redirect_to segments_path, status: :see_other, notice: "Segment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def segment_params
      params.expect(segment: [ :code, :name, :description ])
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_with(model: segment) do |form| %>
  <% if segment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
        <% segment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/segments/_segment.html.erb
<div id="<%= dom_id segment %>">
  <p>
    <strong>Code:</strong>
    <%= segment.code %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= segment.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= segment.description %>
  </p>

</div>

app/views/segments/edit.html.erb
<% content_for :title, "Editing segment" %>

<h1>Editing segment</h1>

<%= render "form", segment: @segment %>

<br>

<div>
  <%= link_to "Show this segment", @segment %> |
  <%= link_to "Back to segments", segments_path %>
</div>

app/views/segments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Segments" %>

<h1>Segments</h1>

<div id="segments">
  <% @segments.each do |segment| %>
    <%= render segment %>
    <p>
      <%= link_to "Show this segment", segment %>
    </p>
  <% end %>
</div>

<%= link_to "New segment", new_segment_path %>

app/views/segments/new.html.erb
<% content_for :title, "New segment" %>

<h1>New segment</h1>

<%= render "form", segment: @segment %>

<br>

<div>
  <%= link_to "Back to segments", segments_path %>
</div>

app/views/segments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @segment %>

<div>
  <%= link_to "Edit this segment", edit_segment_path(@segment) %> |
  <%= link_to "Back to segments", segments_path %>

  <%= button_to "Destroy this segment", @segment, method: :delete %>
</div>