config/routes.rb
Rails.application.routes.draw do
  resources :vehicles do
    resources :vehicle_images
  end
  resources :brands
  resources :vehicle_types
  resources :segments
  resources :fuel_types
  resources :transmissions
  resources :conditions

  root 'vehicles#index'
end

app/models/vehicle_image.rb
class VehicleImage < ApplicationRecord
  belongs_to :vehicle
end

app/controllers/vehicle_images_controller.rb
class VehicleImagesController < ApplicationController
  before_action :set_vehicle_image, only: %i[ show edit update destroy ]

  # GET /vehicle_images or /vehicle_images.json
  def index
    @vehicle_images = VehicleImage.all
  end

  # GET /vehicle_images/1 or /vehicle_images/1.json
  def show
  end

  # GET /vehicle_images/new
  def new
    @vehicle_image = VehicleImage.new
  end

  # GET /vehicle_images/1/edit
  def edit
  end

  # POST /vehicle_images or /vehicle_images.json
  def create
    @vehicle_image = VehicleImage.new(vehicle_image_params)

    respond_to do |format|
      if @vehicle_image.save
        format.html { redirect_to @vehicle_image, notice: "Vehicle image was successfully created." }
        format.json { render :show, status: :created, location: @vehicle_image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_images/1 or /vehicle_images/1.json
  def update
    respond_to do |format|
      if @vehicle_image.update(vehicle_image_params)
        format.html { redirect_to @vehicle_image, notice: "Vehicle image was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle_image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_images/1 or /vehicle_images/1.json
  def destroy
    @vehicle_image.destroy!

    respond_to do |format|
      format.html { redirect_to vehicle_images_path, status: :see_other, notice: "Vehicle image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_image
      @vehicle_image = VehicleImage.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def vehicle_image_params
      params.expect(vehicle_image: [ :vehicle_id, :image_path, :primary_image, :position ])
    end
end

app/helpers/vehicle_images_helper.rb
module VehicleImagesHelper
end

app/views/vehicle_images/_form.html.erb
<%= form_with(model: vehicle_image) do |form| %>
  <% if vehicle_image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vehicle_image.errors.count, "error") %> prohibited this vehicle_image from being saved:</h2>

      <ul>
        <% vehicle_image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :vehicle_id, style: "display: block" %>
    <%= form.text_field :vehicle_id %>
  </div>

  <div>
    <%= form.label :image_path, style: "display: block" %>
    <%= form.text_field :image_path %>
  </div>

  <div>
    <%= form.label :primary_image, style: "display: block" %>
    <%= form.checkbox :primary_image %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_images/_vehicle_image.html.erb
<div id="<%= dom_id vehicle_image %>">
  <p>
    <strong>Vehicle:</strong>
    <%= vehicle_image.vehicle_id %>
  </p>

  <p>
    <strong>Image path:</strong>
    <%= vehicle_image.image_path %>
  </p>

  <p>
    <strong>Primary image:</strong>
    <%= vehicle_image.primary_image %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= vehicle_image.position %>
  </p>

</div>

app/views/vehicle_images/edit.html.erb
<% content_for :title, "Editing vehicle image" %>

<h1>Editing vehicle image</h1>

<%= render "form", vehicle_image: @vehicle_image %>

<br>

<div>
  <%= link_to "Show this vehicle image", @vehicle_image %> |
  <%= link_to "Back to vehicle images", vehicle_images_path %>
</div>

app/views/vehicle_images/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Vehicle images" %>

<h1>Vehicle images</h1>

<div id="vehicle_images">
  <% @vehicle_images.each do |vehicle_image| %>
    <%= render vehicle_image %>
    <p>
      <%= link_to "Show this vehicle image", vehicle_image %>
    </p>
  <% end %>
</div>

<%= link_to "New vehicle image", new_vehicle_image_path %>

app/views/vehicle_images/new.html.erb
<% content_for :title, "New vehicle image" %>

<h1>New vehicle image</h1>

<%= render "form", vehicle_image: @vehicle_image %>

<br>

<div>
  <%= link_to "Back to vehicle images", vehicle_images_path %>
</div>

app/views/vehicle_images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vehicle_image %>

<div>
  <%= link_to "Edit this vehicle image", edit_vehicle_image_path(@vehicle_image) %> |
  <%= link_to "Back to vehicle images", vehicle_images_path %>

  <%= button_to "Destroy this vehicle image", @vehicle_image, method: :delete %>
</div>